### ISSUE TITLE
How to use on full dataset

### ISSUE THREAD

**Issue by myasser63** [Jasonlee1995/AutoAugment_Detection#2]
I tired to use your implementation on my custom dataset. However, I can't figure out how to apply autoaugment policies on my dataset. Could you please help?

**Comment by Jasonlee1995** [comment]
I recommend you to follow the steps below, if you wanna use my codes.

> 1. Edit your dataset file using below link of `COCO dataset`
>    - <img width="500" alt="image" src="https://user-images.githubusercontent.com/49643709/195650268-f99c1274-742c-43cf-979c-36b4ecbd74db.png">
>    - consider about how to make a dataset pair (codes with red rectangles)
> 2. Apply policy with your dataset using policy.py
>    - look tutorials of below link of `Visualization ipynb`

[Visualization ipynb](https://github.com/Jasonlee1995/AutoAugment_Detection/blob/main/Visualize%20-%20Policy.ipynb)
[COCO dataset](https://github.com/Jasonlee1995/AutoAugment_Detection/blob/main/dataset.py)


Besides, there are lots of good opensource repo these days so I recommend to use `albumentations` for applying various augmentations.
(which have more user-friendly guides, tutorials, support, etc...)

[detection task with albumentations](https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/)
